Fix bug of using deprecated function
cuberite/ProtectionAreas pull request #23
Opened 2019-09-02 19:04 UTC by LogicFan

Originally it uses cCuboid::IsInside(double, double, double), which is not supported anymore. I change lua file to use cCuboid::IsInside(Vector3d).

2019-09-02 20:22 UTC, madmaxoft requested changes

2019-09-02 20:22 UTC, madmaxoft commented on PlayerAreas.lua
> +		if (Area.m_Cuboid:IsInside(Vector3d(a_BlockX, 1, a_BlockZ))) then  -- We don't care about Y coords, so use a dummy value
As an optimization, you may want to use a local variable for the `Vector3d` value, so that the object is constructed only once, not for each loop.

2019-09-02 23:45 UTC, LogicFan commented on PlayerAreas.lua
> +		if (Area.m_Cuboid:IsInside(Vector3d(a_BlockX, 1, a_BlockZ))) then  -- We don't care about Y coords, so use a dummy value
Sure, I will change it

2019-09-03 05:39 UTC, madmaxoft requested changes

2019-09-03 05:39 UTC, madmaxoft commented on PlayerAreas.lua
> +		if (Area.m_Cuboid:IsInside(coords)) then  -- We don't care about Y coords, so use a dummy value
The comment should have gone with the ctor.
(sorry for nitpicking)

2020-02-26 20:48 UTC, mathiascode commented
Can the comment be fixed post-merge? I don't have write access to this repo.

2020-02-27 07:36 UTC, merged

2020-02-27 07:37 UTC, madmaxoft commented
Sure

2020-02-27 07:38 UTC, madmaxoft commented
Done.